language: node_js
node_js:
  - "8"
sudo: false
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deploy
      script: bash ./travis/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "9e33f2875b76"
    - COMMIT_AUTHOR_EMAIL: "harry.ickeringill@gmail.com"
