language: node_js
node_js:
- '8'
- '9'
sudo: false
install:
- npm install
jobs:
  include:
    - stage: Test
      script: npm run test
    - stage: Webpack Release
      script: npm run webpack
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: out
        target_branch: webpack
        name: Travis Deploy Bot
        on:
          branch: master
branches:
    except:
    - webpack
cache:
    directories:
    - node_modules
